apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parity-disk
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi